### ISSUE TITLE
ParamManager source file is missing

### ISSUE THREAD

**Issue by mattes3** [wdiestel/arbaro#1]
Hi,
arbaro.java imports net.sourceforge.arbaro.params.ParamManager, however there is no such class in this git repository.

**Comment by wdiestel** [comment]
Hi mattes3,
yes sorry. At some point I tried to refactor the application too much while someone else was adding features without warning me. So I reverted to a status before the refactoring and consolidated it with the added features. Seems I had checked in this consolidated version only to Sourceforge so far: https://sourceforge.net/p/arbaro/code/

But now I updated also the git repo. Hope it is ok now. Please come back if still something is missing.
